#############################################################################
# Makefile for building: bin/TrianglesTest
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  TrianglesTest.pro
# Template: app
# Command: /home/yaroslav/QtLinux5.7.0/5.7/gcc_64/bin/qmake -spec linux-g++ -o Makefile TrianglesTest.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iutils -Istlroutines -I/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/include -I/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/include/QtCore -Irelease/build/moc -I/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/yaroslav/QtLinux5.7.0/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TrianglesTest1.0.0
DISTDIR = /mnt/6a70831d-45da-4f2f-b2b9-e00c4b6fd74c/QtDev/Test_Task_Triangles/TrianglesTest/release/build/obj/TrianglesTest1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = release/build/obj/

####### Files

SOURCES       = utils/comandlineparser.cpp \
		stlroutines/stlfilereader.cpp \
		stlroutines/stlfilewriter.cpp \
		stlroutines/triangle.cpp \
		stlroutines/vertex.cpp \
		stlroutines/surfacesplitter.cpp \
		stlroutines/surface.cpp \
		stlroutines/rect3d.cpp \
		main.cpp 
OBJECTS       = release/build/obj/comandlineparser.o \
		release/build/obj/stlfilereader.o \
		release/build/obj/stlfilewriter.o \
		release/build/obj/triangle.o \
		release/build/obj/vertex.o \
		release/build/obj/surfacesplitter.o \
		release/build/obj/surface.o \
		release/build/obj/rect3d.o \
		release/build/obj/main.o
DIST          = /home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		utils/utils.pri \
		stlroutines/stlroutines.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		TrianglesTest.pro utils/comandlineparser.h \
		stlroutines/stlfilereader.h \
		stlroutines/stlfilewriter.h \
		stlroutines/triangle.h \
		stlroutines/vertex.h \
		stlroutines/surfacesplitter.h \
		stlroutines/surface.h \
		stlroutines/rect3d.h utils/comandlineparser.cpp \
		stlroutines/stlfilereader.cpp \
		stlroutines/stlfilewriter.cpp \
		stlroutines/triangle.cpp \
		stlroutines/vertex.cpp \
		stlroutines/surfacesplitter.cpp \
		stlroutines/surface.cpp \
		stlroutines/rect3d.cpp \
		main.cpp
QMAKE_TARGET  = TrianglesTest
DESTDIR       = bin/
TARGET        = bin/TrianglesTest


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TrianglesTest.pro /home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf /home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		utils/utils.pri \
		stlroutines/stlroutines.pri \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		TrianglesTest.pro \
		/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile TrianglesTest.pro
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
utils/utils.pri:
stlroutines/stlroutines.pri:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
TrianglesTest.pro:
/home/yaroslav/QtLinux5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile TrianglesTest.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents utils/comandlineparser.h stlroutines/stlfilereader.h stlroutines/stlfilewriter.h stlroutines/triangle.h stlroutines/vertex.h stlroutines/surfacesplitter.h stlroutines/surface.h stlroutines/rect3d.h $(DISTDIR)/
	$(COPY_FILE) --parents utils/comandlineparser.cpp stlroutines/stlfilereader.cpp stlroutines/stlfilewriter.cpp stlroutines/triangle.cpp stlroutines/vertex.cpp stlroutines/surfacesplitter.cpp stlroutines/surface.cpp stlroutines/rect3d.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

release/build/obj/comandlineparser.o: utils/comandlineparser.cpp utils/comandlineparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/comandlineparser.o utils/comandlineparser.cpp

release/build/obj/stlfilereader.o: stlroutines/stlfilereader.cpp stlroutines/stlfilereader.h \
		stlroutines/triangle.h \
		stlroutines/vertex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/stlfilereader.o stlroutines/stlfilereader.cpp

release/build/obj/stlfilewriter.o: stlroutines/stlfilewriter.cpp stlroutines/stlfilewriter.h \
		stlroutines/surface.h \
		stlroutines/triangle.h \
		stlroutines/vertex.h \
		stlroutines/rect3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/stlfilewriter.o stlroutines/stlfilewriter.cpp

release/build/obj/triangle.o: stlroutines/triangle.cpp stlroutines/triangle.h \
		stlroutines/vertex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/triangle.o stlroutines/triangle.cpp

release/build/obj/vertex.o: stlroutines/vertex.cpp stlroutines/vertex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/vertex.o stlroutines/vertex.cpp

release/build/obj/surfacesplitter.o: stlroutines/surfacesplitter.cpp stlroutines/surfacesplitter.h \
		stlroutines/surface.h \
		stlroutines/triangle.h \
		stlroutines/vertex.h \
		stlroutines/rect3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/surfacesplitter.o stlroutines/surfacesplitter.cpp

release/build/obj/surface.o: stlroutines/surface.cpp stlroutines/surface.h \
		stlroutines/triangle.h \
		stlroutines/vertex.h \
		stlroutines/rect3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/surface.o stlroutines/surface.cpp

release/build/obj/rect3d.o: stlroutines/rect3d.cpp stlroutines/rect3d.h \
		stlroutines/vertex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/rect3d.o stlroutines/rect3d.cpp

release/build/obj/main.o: main.cpp utils/comandlineparser.h \
		stlroutines/stlfilereader.h \
		stlroutines/triangle.h \
		stlroutines/vertex.h \
		stlroutines/surfacesplitter.h \
		stlroutines/surface.h \
		stlroutines/rect3d.h \
		stlroutines/stlfilewriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/obj/main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

